### ISSUE TITLE
Can't query all users in a gitter room.

### ISSUE THREAD

**Issue by choppsv1** [gitterHQ/docs#14]
I've been trying to query all users in the #syl20bnr/spacemacs gitter room, the room claims there are 2017 users. It only returns 30 or so which does not include even the most active members of the room. One can see this with the curl command:

    curl -i -H "Accept: application/json" -H "Authorization: Bearer <token>" \
      "https://api.gitter.im/v1/rooms/543c742ddb8155e6700cb292/users"

**Comment by MadLittleMods** [comment]
Currently it isn't possible until we implement the skip parameter for pagination. Move discussion to https://github.com/gitterHQ/gitter/issues/1022
