### ISSUE TITLE
Update descriptions for some properties

### ISSUE THREAD

**Issue by NoNameProvided** [gitterHQ/docs#16]
There are a few entity what are not documented:

 - mentions on a message
   ```c#
[JsonObject]
    class Mention
    {
        [JsonProperty(PropertyName = "screenName")]
        public string Id { get; set; }

        [JsonProperty(PropertyName = "userId")]
        public string Username { get; set; }
    }
   ```
 - issues on a message
   ```c#
    [JsonObject]
    class Issue
    {
        [JsonProperty(PropertyName = "number")]
        public int Number { get; set; }
    }

   ```
 - `meta` property on a message
 - possible values of the `security` property
 - user's `gv` property

I understand that the API is still under development, but not having a proper documentation is making it really hard to build any solution on the top of it. Of course I don't expect a fully detailed documentation, but at least write a sentence about every property, and **keep the scheme descriptions up to date**

**Comment by MadLittleMods** [comment]
Feel free to create a pull request:

 - The `mentions` property  can look like the following but is listed in the message schema: https://developer.gitter.im/docs/messages-resource#message-schema
```
"mentions": [
            {
                "screenName": "MadLittleMods",
                "userId": "xxx",
                "userIds": []
            }
        ],

"mentions": [
            {
                "screenName": "all",
                "userIds": [
                    "xxx"
                ],
                "group": true
            }
        ],
```


 - The `meta` property isn't used for anything but is listed in the message schema: https://developer.gitter.im/docs/messages-resource#message-schema
 - `security` can be `INHERITED` `PUBLIC` and `PRIVATE`
 - `gv` is cache busting version used for avatars
