### ISSUE TITLE
sign in button is hidden

### ISSUE THREAD

**Issue by dervondenbergen** [gitterHQ/docs#2]
When trying to sign in, it is not possible because the "Fork me on GitHub" badge is over the button.

Only way to press the button is to remove the badge with something like the dev tools.

![screen shot 2015-03-25 at 18 34 25](https://cloud.githubusercontent.com/assets/2054024/6830952/a63c7076-d31d-11e4-9e9d-9fa2d3698bfa.png)

**Comment by malditogeek** [comment]
Fixed.
