### ISSUE TITLE
Make the bot appear online

### ISSUE THREAD

**Issue by haggen** [gitterHQ/docs#36]
I made a bot that consumes the stream API to listen to messages and react accordingly but I wanted to make it appear online so people know he's there.

Is there some kind of ping/heartbeat I can send to the room to make it appear online?

---

:point_up: [July 24, 2016 10:18 AM](https://gitter.im/gitterHQ/developers?at=5794dc3bb92e27447faeccf8)

**Comment by MadLittleMods** [comment]
`GET /v1/eyeballs` with `{ socketId: xxx, on: 1 }` data

**Comment by haggen** [comment]
Do I have to make this request only once or every few seconds? Also where does the `socketId` come from?

**Comment by MadLittleMods** [comment]
@haggen Updated last reply

**Comment by haggen** [comment]
Thanks!

**Comment by haggen** [comment]
Quick question, @MadLittleMods: do I have to post using the REST API or does Faye accept that I publish messages from my client to the server?

**Comment by MadLittleMods** [comment]
@haggen Post via the REST API. I recommend using the [Halley](https://github.com/gitterHQ/halley) client which has [`getClientId`](https://github.com/gitterHQ/halley/blob/ea3c3e0a67bd2a7d1ca2a3e3980577ea7da77ca7/lib/protocol/client.js#L202) but looks like you may be using Ruby and in reality any bayeux client should do.

I'm not familiar with Ruby so it's a bit hard for me to suss out the way they want you to get the client ID in the [Ruby faye/faye code](https://github.com/faye/faye/blob/master/lib/faye/protocol/client.rb). I am not seeing `client._dispatch` as you describe but does this work `client.dispatcher.client_id`?

**Comment by haggen** [comment]
@MadLittleMods I'm using JavaScript but I just noticed that you used Halley instead of the the faye standard client. I'll try with it. Thanks a lot for everything! The page about the faye docs would benefit from a message telling that we should use the REST API to send information, may I send you a PR?

**Comment by MadLittleMods** [comment]
@haggen PR is welcome :grinning:
