### ISSUE TITLE
Jabber

### ISSUE THREAD

**Issue by blasterbug** [gitterHQ/docs#4]
Is it possible to use Gitter with a jabber app ? 
And in a near future ?
Thanks.

**Comment by malditogeek** [comment]
Hi @blasterbug, sorry for the delay, I missed this comment. This is the repo for the documentation, we keep another repo for support/questions: https://github.com/gitterHQ/gitter/issues

There's an issue open for XMPP support but we don't have it yet:  https://github.com/gitterHQ/gitter/issues/248

We have IRC tho: https://irc.gitter.im
